name: DSPipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  DockerBuildPublish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/mydsapp:latest
          docker build -t $IMAGE_NAME .
          echo "Built image: $IMAGE_NAME"

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/mydsapp:latest
          docker push $IMAGE_NAME